name: Lint PHP

on:
    push:
      paths:
        - '**/*.php'
    pull_request:
      paths:
        - '**/*.php'

jobs:
  lint:
    name: PHP Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Install PHPStan
        run: |
          composer global require phpstan/phpstan

      - name: Run PHPStan
        run: |
          phpstan analyse --level=max --no-progress .

      - name: Run PHP lint
        run: |
          find . -name "*.php" -print0 | xargs -0 -n1 php -l
